-- ===========================================================================
-- MonPortefeuille 2.0 — comptes de liquidités
--
-- Remplace les liquidités « déguisées » de la table v1 `Donnees` (pseudo-tickers
-- USD / CHF / CNY) par de vrais comptes : nom, banque, devise, type
-- (réserve / disponible) et motif, alimentés par des opérations.
--
-- À exécuter dans Supabase : SQL Editor > New query > coller ce fichier > Run.
-- Prérequis : 001_init.sql (tables pf2_transactions et pf2_apports).
-- Nommé 003 et non 002 : 002_rls.sql existe déjà.
--
-- IDEMPOTENT : chaque instruction peut être rejouée sans erreur
-- (create ... if not exists, drop policy if exists, enable RLS déjà actif).
--
-- Ne modifie aucune table existante. La v1 et le robot nocturne continuent de
-- lire `Donnees` pendant la transition ; la migration des soldes est faite par
-- l'application au premier lancement 2.0 (table pf2_comptes vide).
--
-- Retour arrière (si besoin) :
--   drop table if exists pf2_operations_compte;
--   drop table if exists pf2_comptes;
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- pf2_comptes — un compte de liquidités.
--
-- Le SOLDE n'est jamais stocké. Il se calcule comme la somme signée des
-- opérations du compte (pf2_operations_compte). Une seule source de vérité.
--
-- type :
--   'reserve'    épargne de précaution, jamais investie, jamais proposée à
--                l'achat ou à la vente de titres.
--   'disponible' compte courant : achats et ventes de titres de sa devise.
--
-- archive : un compte n'est jamais supprimé. Archivé, il disparaît des listes
--           mais garde son historique et reste compté dans le patrimoine.
-- ---------------------------------------------------------------------------
create table if not exists pf2_comptes (
    id          text primary key,          -- identifiant généré par l'application
    nom         text not null,             -- « Livret CHF », « Courtage USD »…
    banque      text,                      -- texte libre ; l'application propose les banques déjà saisies
    devise      text not null,             -- code ISO 4217 : 'USD', 'CHF', 'CNY', 'EUR'…
    type        text not null check (type in ('reserve', 'disponible')),
    motif       text,                      -- pourquoi ce compte existe
    archive     boolean not null default false,
    note        text,
    cree_le     timestamptz default now(),
    modifie_le  timestamptz default now()
);


-- ---------------------------------------------------------------------------
-- pf2_operations_compte — chaque mouvement d'un compte.
--
-- montant : dans la DEVISE du compte, signé.
--           > 0 : l'argent entre sur le compte.   < 0 : l'argent en sort.
--
-- type :
--   ouverture     solde initial (y compris la migration depuis Donnees)
--   depot         apport de fonds (lié à pf2_apports via apport_id)
--   retrait       retrait de fonds (lié à pf2_apports via apport_id)
--   virement      une jambe d'un virement entre deux comptes
--   achat_titres  achat (lié à pf2_transactions via transaction_id)
--   vente_titres  vente (lié à pf2_transactions via transaction_id)
--   frais         frais de compte
--
-- groupe : identifiant de COUPLAGE des deux jambes d'un virement (un uuid
--          commun à la sortie et à l'entrée). Modifier ou supprimer une jambe
--          agit sur les deux. NULL pour toute autre opération.
--
-- contrepartie : identifiant du compte D'EN FACE dans un virement. Affiché
--          « → Livret CHF » (sortie) ou « ← Courtage USD » (entrée).
--          NULL pour toute autre opération. Pas de clé étrangère : un compte
--          n'est jamais supprimé, il est archivé.
--
-- apport_id : lien vers pf2_apports. Supprimer un apport SUPPRIME son
--          opération de compte (on delete cascade) : aucun mouvement orphelin,
--          donc aucun double comptage.
--
-- transaction_id : lien vers pf2_transactions. Même règle : supprimer une
--          transaction supprime son opération de compte.
--
-- Un virement écrit DEUX lignes (sortie sur la source, entrée sur la cible),
-- avec le même `groupe`, chacune portant l'id du compte d'en face dans
-- `contrepartie`. Les deux lignes sont écrites en une seule requête.
-- ---------------------------------------------------------------------------
-- `by default` (et non `always`) : la modification d'un virement réécrit ses
-- deux jambes en UN upsert sur leurs id. Avec `always`, PostgreSQL refuse un
-- id explicite.
create table if not exists pf2_operations_compte (
    id             bigint generated by default as identity primary key,
    compte_id      text not null references pf2_comptes (id),
    type           text not null check (type in
                     ('ouverture', 'depot', 'retrait', 'virement',
                      'achat_titres', 'vente_titres', 'frais')),
    montant        numeric not null,
    date           date not null,
    contrepartie   text,
    groupe         text,
    transaction_id bigint references pf2_transactions (id) on delete cascade,
    apport_id      bigint references pf2_apports (id) on delete cascade,
    note           text,
    cree_le        timestamptz default now()
);

create index if not exists pf2_operations_compte_compte_idx
    on pf2_operations_compte (compte_id, date);
create index if not exists pf2_operations_compte_groupe_idx
    on pf2_operations_compte (groupe);
create index if not exists pf2_operations_compte_transaction_idx
    on pf2_operations_compte (transaction_id);
create index if not exists pf2_operations_compte_apport_idx
    on pf2_operations_compte (apport_id);


-- ---------------------------------------------------------------------------
-- Row Level Security — même politique que 002_rls.sql.
-- Accordée aux rôles `anon` (clé publique saisie dans l'application) et
-- `authenticated` : select, insert, update et delete (`for all`).
-- SANS ce bloc, RLS actif sans politique : les lectures renvoient zéro ligne et
-- les écritures échouent en 42501 (voir 002_rls.sql pour le détail).
-- Portée limitée aux deux tables de 2.0 ; la v1 n'est pas touchée.
-- ---------------------------------------------------------------------------
alter table pf2_comptes enable row level security;
alter table pf2_operations_compte enable row level security;

drop policy if exists pf2_acces_public on pf2_comptes;
create policy pf2_acces_public on pf2_comptes
    for all
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists pf2_acces_public on pf2_operations_compte;
create policy pf2_acces_public on pf2_operations_compte
    for all
    to anon, authenticated
    using (true)
    with check (true);
