-- ===========================================================================
-- MonPortefeuille 2.0 — comptes de liquidités
--
-- Remplace les liquidités « déguisées » de la table v1 `Donnees` (pseudo-tickers
-- USD / CHF / CNY) par de vrais comptes : nom, banque, devise, type
-- (réserve / disponible) et motif, alimentés par des opérations.
--
-- Nommé 003 et non 002 : 002_rls.sql existe déjà. À exécuter une seule fois
-- dans l'éditeur SQL de Supabase, après 001_init.sql et 002_rls.sql.
-- Ne modifie aucune table existante : la v1 et le robot nocturne continuent
-- de lire `Donnees` pendant la transition.
--
-- Retour arrière (si besoin) :
--   drop table if exists pf2_operations_compte;
--   drop table if exists pf2_comptes;
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Comptes. Le solde n'est JAMAIS stocké : il se calcule comme la somme signée
-- des opérations du compte. Une seule source de vérité.
-- ---------------------------------------------------------------------------
create table if not exists pf2_comptes (
    id          text primary key,          -- uuid généré par l'application
    nom         text not null,             -- « Livret CHF », « Courtage USD »…
    banque      text,                      -- texte libre (suggestions côté app)
    devise      text not null,             -- ISO 4217 : 'USD', 'CHF', 'CNY', 'EUR'…
    type        text not null check (type in ('reserve', 'disponible')),
    motif       text,                      -- pourquoi ce compte existe
    archive     boolean not null default false,
    note        text,
    cree_le     timestamptz default now(),
    modifie_le  timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- Opérations. `montant` est dans la DEVISE du compte, signé :
-- > 0 = argent qui entre, < 0 = argent qui sort.
--
-- Un virement écrit DEUX opérations (sortie sur la source, entrée sur la cible)
-- qui partagent le même `groupe`. `contrepartie` porte l'id du compte de
-- l'autre jambe. (Le cahier des charges mélangeait les deux usages dans
-- `contrepartie` ; on sépare : `contrepartie` = compte, `groupe` = lien.)
--
-- `transaction_id` et `apport_id` : suppression en cascade. Supprimer une
-- transaction ou un apport supprime sa propre écriture de compte : aucun
-- mouvement orphelin, donc aucun double comptage.
-- ---------------------------------------------------------------------------
-- `by default` (et non `always`) : la modification d'un virement réécrit les deux
-- jambes en UN upsert sur leurs id ; avec `always`, PostgreSQL refuse un id explicite.
create table if not exists pf2_operations_compte (
    id             bigint generated by default as identity primary key,
    compte_id      text not null references pf2_comptes (id),
    type           text not null check (type in
                     ('ouverture', 'depot', 'retrait', 'virement',
                      'achat_titres', 'vente_titres', 'frais')),
    montant        numeric not null,
    date           date not null,
    contrepartie   text,                   -- id du compte de l'autre jambe (virement)
    groupe         text,                   -- uuid commun aux deux jambes d'un virement
    transaction_id bigint references pf2_transactions (id) on delete cascade,
    apport_id      bigint references pf2_apports (id) on delete cascade,
    note           text,
    cree_le        timestamptz default now()
);

create index if not exists pf2_operations_compte_compte_idx
    on pf2_operations_compte (compte_id, date);
create index if not exists pf2_operations_compte_groupe_idx
    on pf2_operations_compte (groupe);
create index if not exists pf2_operations_compte_transaction_idx
    on pf2_operations_compte (transaction_id);
create index if not exists pf2_operations_compte_apport_idx
    on pf2_operations_compte (apport_id);

-- ---------------------------------------------------------------------------
-- Row Level Security — même politique que 002_rls.sql. SANS ce bloc, RLS actif
-- sans politique : les lectures renvoient zéro ligne et les écritures échouent
-- en 42501 (voir 002_rls.sql pour le détail de ce piège).
-- ---------------------------------------------------------------------------
alter table pf2_comptes enable row level security;
alter table pf2_operations_compte enable row level security;

drop policy if exists pf2_acces_public on pf2_comptes;
create policy pf2_acces_public on pf2_comptes
    for all
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists pf2_acces_public on pf2_operations_compte;
create policy pf2_acces_public on pf2_operations_compte
    for all
    to anon, authenticated
    using (true)
    with check (true);
